@startuml internal-ssd
label l [

{{
title Input

actor user
participant InputController
participant InputValidator
participant InputDisplayer

loop Inserimento fino a input valido
    user -> InputController: inputSentence
    InputController -> InputValidator: verifyInput(input)
    InputValidator --> InputController: boolean

    alt input non valido
        InputController -> InputDisplayer: showInputError()
    end
end

InputController -> InputDisplayer: displayInput(input)
InputDisplayer -> user: mostra frase
}}

{{
title Analysis

actor user
participant AnalysisController
participant SentenceValidator
participant TreeDisplayer
participant GoogleAPI

loop Processo di analisi
    user -> AnalysisController: InputProcess
    AnalysisController -> GoogleAPI: getSyntacticTree(input)
    GoogleAPI --> AnalysisController: syntacticTree
    AnalysisController -> SentenceValidator: validateSentence(syntacticTree)
    SentenceValidator --> AnalysisController: boolean

    alt Frase non valida
        AnalysisController -> user: showValidationError
    end
end

opt Mostra struttura sintattica
    user -> AnalysisController: showSyntacticTree
    AnalysisController -> TreeDisplayer: getTree(syntacticTree)
    TreeDisplayer --> user: syntacticStructure
end
}}

{{
title TemplateGeneration

actor user
participant TemplateController
participant TemplateGenerator
participant TemplateStorage

TemplateController -> TemplateGenerator: generateTemplate(tree)
TemplateGenerator --> TemplateController: template
TemplateController -> TemplateStorage: handleTemplate(template)
}}

]
@enduml