@startuml Internal SSD
label l [

{{

title Input

actor user
participant IOController
participant Validator
participant SentenceController

loop Inserimento fino a input valido

    user -> IOController: inputSentence(input)
    IOController -> Validator: verifySentence(input)
    alt input non valido
        Validator -> IOController: showInputError()
        IOController --> user : inputError 
    end
end

Validator -> SentenceController : createSentence(input) 
SentenceController -> Sentence ++ : create(input)
Sentence --> SentenceController : sentenceDesc
SentenceController -> IOController : displaySentence(sentenceDesc)
IOController --> user : sentenceDesc

}}


{{

title Analysis

actor user
participant IOController
participant Validator
participant Analyzer
participant SyntacticNode
participant SentenceController

loop Processo di analisi

    user -> Sentence ++ : inputProcess
    participant ApiCaller
    participant GoogleAPI

    SentenceController -> Analyzer : analyzeSentence(sentenceDesc)
    Analyzer -> ApiCaller: getSyntaxAnalysis(sentenceDesc)
    ApiCaller -> GoogleAPI: analyzeSyntax(apiKey, sentenceDesc)
    GoogleAPI --> ApiCaller: syntaxAnalysis
    ApiCaller --> Analyzer: syntaxAnalysis
    Analyzer -> Analyzer: buildSyntacticTree(syntaxAnalysis)
    Analyzer -> SyntacticNode: addChild(child, dependency)
    Analyzer --> SentenceController: syntacticTree
    SentenceController --> Sentence : syntacticTree
    SentenceController -> Validator: validateSentenceStructure(syntacticTree)
    alt Frase non valida
        Validator -> IOController: showValidationError()
        IOController --> user : validationError
    end
end

opt Mostra struttura sintattica

    user -> IOController: showSyntacticTree()
    IOController -> SentenceController: getSyntacticTree()
    SentenceController --> IOController: syntacticTree
    IOController --> user : syntacticTree

end

}}


{{

title TemplateGeneration

actor user
participant TemplateController
participant TemplateGenerator
participant SentenceStructures

user -> TemplateController : inputProcess
TemplateController -> TemplateGenerator: generateTemplate(sentenceStructure)
TemplateGenerator -> SentenceStructures: getRandomStructure()
SentenceStructures --> TemplateGenerator: randomStructure
TemplateGenerator -> Template ++: create(templateDesc, templateWords[])
TemplateGenerator --> TemplateController: templateDesc, templateWords[] 

}}


{{

title WordsExtraction

participant TemplateController
participant WordPicker
participant SentenceController
participant SystemDictionary
participant Nouns
participant Verbs
participant Adjectives

WordPicker -> TemplateController : getWordCount()
TemplateController --> WordPicker : templateWords[]
WordPicker -> SentenceController : getSyntacticTree()
SentenceController --> WordPicker : syntacticTree
WordPicker -> WordPicker : pickSentenceWords()
WordPicker -> SystemDictionary : pickDictionaryWords(dictionaryWords[])
SystemDictionary -> Nouns : getNouns(nounsCount)
SystemDictionary <-- Nouns : nouns[]
SystemDictionary -> Verbs : getVerbs(verbsCount)
SystemDictionary <-- Verbs : verbs[]
SystemDictionary -> Adjectives : getAdjectives(adjectivesCount)
SystemDictionary <-- Adjectives : adjectives[]
SystemDictionary -> SystemDictionary : createDictionary(nouns[], verbs[], adjectives[])
WordPicker <-- SystemDictionary : dictionary

}}

    
{{

title SentenceGeneration

participant SentenceGenerator
participant SentenceController
participant WordPicker
participant TemplateController

SentenceGenerator -> SentenceController : getTemplateDesc()
SentenceController -> TemplateController : getTemplateDesc()
SentenceGenerator <-- TemplateController : templateDesc
SentenceGenerator -> SentenceController : getWords()
SentenceController -> WordPicker : getWords()
SentenceGenerator <-- WordPicker : words[]
SentenceGenerator -> SentenceGenerator : generateSentence()
SentenceGenerator -> SentenceController : createSentence(sentenceDesc)
SentenceController -> Sentence ++ : create(sentenceDesc)
SentenceController <-- Sentence : sentenceDesc

}}


{{

title ToxicityEvaluation

actor user
participant IOController
participant WordPicker
participant SentenceGenerator
participant SentenceController
participant Validator 
participant ApiCaller
participant GoogleAPI

loop Analisi tossicità

alt Rigenerazione da input

user -> WordPicker : InputProcess

end

WordPicker -> SentenceGenerator : WordPickingProcess
SentenceGenerator -> SentenceController : SentenceGenerationProcess
SentenceController -> Validator : verifyToxicity(sentenceDesc)
Validator -> ApiCaller : getToxicityAnalysis(sentenceDesc)
ApiCaller -> GoogleAPI : moderateText(apiKey, sentenceDesc)
ApiCaller <-- GoogleAPI : toxicityAnalysis
Validator <-- ApiCaller : toxicityAnalysis
alt Frase tossica

Validator -> IOController : showToxicityError()
IOController --> user : toxicityError

end

end

IOController <- Validator : showToxicityResults(toxicityLabel, toxicityLevel)
IOController --> user : toxicityResults

}}


{{

title DisplaySentence

actor user
participant IOController
participant SentenceController

SentenceController -> IOController : displaySentence(sentenceDesc)
IOController --> user: sentenceDesc

}}

]

@enduml