@startuml internal-ssd
label l [

{{

title Input /'OK'/

actor user
participant IOController
participant Validator
participant SentenceProcessor

loop Inserimento fino a input valido

    user -> IOController: inputSentence(input)
    IOController -> Validator: verifySentence(input)
    alt input non valido
        Validator -> IOController: showInputError()
        IOController --> user : inputError 
    end
end

Validator -> SentenceProcessor : createSentence(input) 
SentenceProcessor -> Sentence ++ : create(input)/'costruttore'/
Sentence --> SentenceProcessor : sentenceDesc
SentenceProcessor -> IOController : displaySentence(sentenceDesc)
IOController --> user : sentenceDesc

}}


{{

title Analysis /'OK'/

actor user
participant IOController
participant Validator
participant Analyzer
participant SyntacticNode
participant SentenceProcessor

loop Processo di analisi

    user -> Sentence ++ : inputProcess
    participant ApiCaller
    participant GoogleAPI

    SentenceProcessor -> Analyzer : analyzeSentence(sentenceDesc)
    Analyzer -> ApiCaller: getSyntaxAnalysis(sentenceDesc)
    ApiCaller -> GoogleAPI: analyzeSyntax(apiKey, sentenceDesc)
    GoogleAPI --> ApiCaller: syntaxAnalysis
    ApiCaller --> Analyzer: syntaxAnalysis
    Analyzer -> Analyzer: buildSyntacticTree(syntaxAnalysis)
    Analyzer -> SyntacticNode: addChild(child, dependency)
    Analyzer --> SentenceProcessor: syntacticTree
    SentenceProcessor --> Sentence : syntacticTree
    SentenceProcessor -> Validator: validateSentenceStructure(syntacticTree)
    alt Frase non valida
        Validator -> IOController: showValidationError()
        IOController --> user : validationError
    end
end

opt Mostra struttura sintattica

    user -> IOController: showSyntacticTree()
    IOController -> SentenceProcessor: getSyntacticTree()
    SentenceProcessor --> IOController: syntacticTree
    IOController --> user : syntacticTree

end

}}


{{

title TemplateGeneration /'OK'/

actor user
participant TemplateController
participant TemplateGenerator
participant SentenceStructures

user -> TemplateController : inputProcess
TemplateController -> TemplateGenerator: generateTemplate()
TemplateGenerator -> SentenceStructures: getRandomStructure()
SentenceStructures --> TemplateGenerator: randomStructure
TemplateGenerator -> Template ++: create(randomStructure)
Template --> TemplateGenerator: templateDesc,templateWords[]
TemplateGenerator --> TemplateController: templateDesc, templateWords[] 

}}


{{

title WordsExtraction /'OK'/

participant TemplateController
participant WordPicker
participant SentenceProcessor
participant SystemDictionary
participant Nouns
participant Verbs
participant Adjectives

WordPicker -> TemplateController : getWordCount()
TemplateController --> WordPicker : templateWords[]
WordPicker -> SentenceProcessor : getSyntacticTree()
SentenceProcessor --> WordPicker : syntacticTree
WordPicker -> WordPicker : pickSentenceWords(senWords[])
WordPicker -> SystemDictionary : pickDictionaryWords(dicWords[])
SystemDictionary -> Nouns : getNouns(nounsCount)
SystemDictionary <-- Nouns : nouns[]
SystemDictionary -> Verbs : getVerbs(verbsCount)
SystemDictionary <-- Verbs : verbs[]
SystemDictionary -> Adjectives : getAdjectives(adjectivesCount)
SystemDictionary <-- Adjectives : adjectives[]
SystemDictionary -> SystemDictionary : createDictionary(nouns[], verbs[], adjectives[])
WordPicker <-- SystemDictionary : dictionary

}}

    
{{

title SentenceGeneration /'OK'/

participant SentenceGenerator
participant WordPicker
participant TemplateController
participant SentenceProcessor

SentenceGenerator -> TemplateController : getTemplateDesc()
SentenceGenerator <-- TemplateController : templateDesc
SentenceGenerator -> WordPicker : getWords()
SentenceGenerator <-- WordPicker : words[]
SentenceGenerator -> SentenceGenerator : generateSentenceDesc(templateDesc,words[])
SentenceGenerator -> SentenceProcessor : createSentence(sentenceDesc)
SentenceProcessor -> Sentence ++ : create(sentenceDesc)/'costruttore'/
SentenceProcessor <-- Sentence : sentenceDesc

}}


{{

title ToxicityEvaluation /'OK'/

actor user
participant IOController
participant WordPicker
participant SentenceGenerator
participant SentenceProcessor
participant Validator 
participant ApiCaller
participant GoogleAPI

loop Analisi tossicità

WordPicker -> SentenceGenerator : WordPickingProcess
SentenceGenerator -> SentenceProcessor : SentenceGenerationProcess
SentenceProcessor -> Validator : verifyToxicity(sentenceDesc)
Validator -> ApiCaller : getToxicityAnalysis(sentenceDesc)
ApiCaller -> GoogleAPI : moderateText(apiKey, sentenceDesc)
ApiCaller <-- GoogleAPI : toxicityAnalysis
Validator <-- ApiCaller : toxicityAnalysis
alt Frase tossica

Validator -> IOController : showToxicityError()
IOController --> user : toxicityError

end

end

IOController <- Validator : showToxicityResults(toxicityLevel)
IOController --> user : toxicityResults

}}


{{

title DisplaySentence /'OK'/

actor user
participant IOController
participant SentenceProcessor


SentenceProcessor -> IOController : displaySentence(sentenceDesc)
IOController --> user: sentenceDesc

}}

]
@enduml