@startuml Design Class Model

    class AppController {
        start() : void
        getValidSentence() : String
        createTemplateController() : TemplateController
    }

    class IOController {
        scanner : Scanner
        inputSentence() : String
        showInputError() : void
        displaySentence(sentenceDesc : String, flag : int) : void
        showValidationError() : void
        showSyntacticTree() : void
        showToxicityError() : void
        showToxicityResults(toxicityLabel : String, toxicityLevel : double) : void
    }

    class Sentence {
        sentenceDesc : String
        syntacticTree : SyntacticNode
        setSentenceTree(syntacticTree : SyntacticNode) : void
        getSentenceDesc() : String
        getSentenceTree() : SyntacticNode
    }

    class SentenceProcessor {
        inputSentence : Sentence
        nonSenseSentence : Sentence
        currentSentence : Sentence
        state : boolean
        createSentence(sentenceDesc : String) : void
        getSyntacticTree() : SyntacticNode
    }
    
    class Validator {
        verifySentence(input : String) : boolean
        validateSentenceStructure(syntacticTree : SyntacticNode) : boolean
        verifyToxicity(sentenceDesc : String) : boolean
    }

    class Analyzer {
        analyzeSentence(sentenceDesc : String) : void
        buildSyntacticTree(jsonInput : String) : SyntacticNode
    }

    class ApiCaller {
        getSyntaxAnalysis(sentenceDesc : String) : String
        getToxicityAnalysis(sentenceDesc : String) : String
        getApiKey() : String
        makeCall(url : String, payload : String) : String
    }

    /'GoogleAPI non è realmente una classe del nostro sistema'/

    class Template {
        templateDesc : String
        templateWords : int[]
        combinations : Map<Integer, List<int[]>>
        create(randomStructure : String) : Template
    }

    class TemplateController {
        template : Template
        getWordCount() : int[]
        getTemplateDesc() : String
    }

    class TemplateGenerator {
        s : SentenceStructures
        generateTemplate() : Template
    }

    class SentenceStructures {
        structures : File
        getRandomStructure() : String
    }
    
    class Nouns {
        nouns : List<String>
        getNouns(count : int) : List<String>
    }

    class Verbs {
        verbs : List<String>
        getVerbs(count : int) : List<String>
    }

    class Adjectives {
        adjectives : List<String>
        getAdjectives(count : int) : List<String>
    }

    class SystemDictionary {
        nouns : Nouns
        verbs : Verbs
        adjectives : Adjectives
        createDictionary(nouns : List<String>, verbs : List<String>, adjectives : List<String>) : Map<String, List<String>>
        setupWordDic() : void
        initializeDic() : void
        pickDictionaryWords(words : int[]) : Map<String, List<String>>
    }
    
    class WordPicker {
        numOfRetries : int
        generatedWords : Map<String, List<String>>
        startWordsExtraction(controller : TemplateController) : void
        pickSentenceWords() : void
        getWords() : Map<String, List<String>>
        analyzeSyntacticTree(syntactictree : SyntacticNode) : void
        loopOnNodes(node : SyntacticNode) : void
        resetNumOfRetries() : void
    }

    class SentenceGenerator {
        sentenceDesc : String
        fillingWords : Map<String, List<String>>
        generateSentenceDesc(controller : TemplateController) : void
    }

    class SyntacticNode {
        text : String
        lemma : String
        partOfSpeech : String
        dependency : String
        node : List<SyntacticNode>
        addChild(child : SyntacticNode, dependency : String) : void
        printTree(root : String) : void
    }

    /'
    ' --- contenimento e creazione ---
    TemplateGenerator *-- "1" SentenceStructures
    SystemDictionary *-- "1" Nouns
    SystemDictionary *-- "1" Verbs
    SystemDictionary *-- "1" Adjectives
    TemplateController *-- "1" Template
    TemplateGenerator ..> Template : <<create>>

    ' --- dipendenze principali dell'app ---
    AppController ..> IOController
    AppController ..> Validator
    AppController ..> SentenceProcessor
    AppController ..> TemplateController

    ' --- IO / validazione / processing ---
    IOController ..> Validator
    IOController ..> SentenceProcessor

    SentenceProcessor *-- "0..1" Sentence : current
    SentenceProcessor *-- "0..1" Sentence : nonsense
    Sentence *-- "1" SyntacticNode : root
    SyntacticNode *-- "0..*" SyntacticNode : children

    ' --- generator & word picking ---
    SentenceGenerator ..> TemplateController
    SentenceGenerator ..> WordPicker
    SentenceGenerator ..> SentenceProcessor
    WordPicker ..> SystemDictionary

    ' --- analisi sintattica ---
    Analyzer ..> ApiCaller
    Analyzer ..> SyntacticNode
    Analyzer ..> SentenceProcessor

    Validator ..> ApiCaller
    Validator ..> IOController
    Validator ..> SyntacticNode
    '/

    /'
        Vecchi collegamenti per confronto
        SentenceStructures o- TemplateGenerator
        Nouns -* SystemDictionary
        Verbs -* SystemDictionary
        Adjectives -* SystemDictionary

        IOController "1" -- "1" Validator
        IOController "1" -- "1" SentenceProcessor
        Sentence "*"--"1" SentenceProcessor
        SentenceProcessor "1" -- "1" Validator
        SentenceProcessor "1" -- "1" Analyzer
        SentenceProcessor "1" -- "1" SentenceGenerator
        TemplateGenerator "1" -- "1" Template
        TemplateController "1" -- "1" TemplateGenerator
        TemplateController "1" -- "1" WordPicker
        WordPicker "1" -- "1" SystemDictionary
        WordPicker "1" -- "1" SentenceProcessor
        ApiCaller "1" -- "1" Validator
        ApiCaller "1" -- "1" Analyzer
        SyntacticNode "1" -- "1" Analyzer 
    '/

    Nouns -* SystemDictionary
    Verbs -* SystemDictionary
    Adjectives -* SystemDictionary
    SyntacticNode -* Sentence
    SentenceStructures o- TemplateGenerator

    App "1" -- "1" AppController

    AppController "1" -- "1" IOController
    AppController "1" -- "1" SentenceProcessor
    AppController "1" -- "1" SentenceStructures
    AppController "1" -- "1" TemplateController
    AppController "1" -- "1" WordPicker

    IOController "1" -- "1" SentenceProcessor
    IOController "1" -- "1" Validator

    Sentence "*"--"1" SentenceProcessor
    SentenceProcessor "1" -- "1" SentenceGenerator
    SentenceProcessor "1" -- "1" Analyzer
    SentenceProcessor "1" -- "1" Validator
    Analyzer "1" -- "1" ApiCaller
    Validator "1" -- "1" ApiCaller
    
    Template "1" -- "1" TemplateGenerator
    TemplateGenerator "1" -- "1" TemplateController
    TemplateController "1" -- "1" WordPicker
    
    WordPicker "1" -- "1" SentenceProcessor
    WordPicker "1" -- "1" SystemDictionary

@enduml