@startuml Design Model

    class IOController { /'OK'/
        inputSentence(input : String) : void
        showInputError() : void
        displaySentence(sentenceDesc : String) : void
        showValidationError() : void
        showSyntacticTree() : void
        showToxicityError() : void
        showToxicityResults() : void
    }

    class Sentence { /'OK'/
        sentenceDesc : String
        <<syntacticTree>>
        create(sentenceDesc : String) : Sentence
    }

    class SentenceProcessor { /'OK'/
        inputSentence : Sentence
        nonSenseSentence : Sentence
        createSentence(sentenceDesc : String) : Sentence
        getSyntacticTree() : <<syntacticTree>>
    }
    
    class Validator { /'OK'/
        verifySentence(sentenceDesc : String) : void
        validateSentenceStructure(syntacticTree : <<syntacticTree>>) : void
        verifyToxicity(sentenceDesc : String) : void
    }

    class Analyzer { /'OK'/
        analyzeSentence(sentenceDesc : String) : <<syntacticTree>>
    }

    class ApiCaller { /'OK'/
        getSyntaxAnalysis(sentenceDesc : String) : <<syntacticTree>>
        getToxicityAnalysis(sentenceDesc : String) : <<toxicityAnalysis>>
    }

    /'GoogleAPI non è realmente una classe del nostro sistema'/

    class Template { /'OK'/
        templateDesc : String
        templateWords : int[]
        create(randomStructure : <<structures>>) : Template
    }

    class TemplateController { /'OK'/
        template : Template
        getWordCount() : int[]
        getTemplateDesc() : String
    }

    class TemplateGenerator { /'OK'/
        generateTemplate() : Template
    }

    class SentenceStructures { /'OK'/
        <<structures>>
        getRandomStructure() : <<structures>>
    }
    
    class Nouns { /'OK'/
        nouns : String[]
        getNouns(nounsCount : int) : String[]
    }

    class Verbs { /'OK'/
        verbs : String[]
        getVerbs(verbsCount : int) : String[]
    }

    class Adjectives { /'OK'/
        adjectives : String[]
        getAdjectives(adjectivesCount : int) : String[]
    }

    class SystemDictionary { /'OK'/
        nouns : Nouns
        verbs : Verbs
        adjectives : Adjectives
        dictionary : Dictionary<K,V>
        createDictionary(nouns : String[], verbs : String[], adjectives : String[]) : Dictionary<K,V>
        pickDictionaryWords(dicWords : int[]) : Dictionary<K,V>
    }
    
    class WordPicker { /'OK'/
        pickSentenceWords(senWords : int[]) : String[]
        getWords() : Dictionary<K,V>
    }

    class SentenceGenerator { /'OK'/
        generateSentenceDesc(templateDesc : String, words : Dictionary<K,V>) : String
    }

    SentenceStructures o- TemplateGenerator
    Nouns -* SystemDictionary
    Verbs -* SystemDictionary
    Adjectives -* SystemDictionary

    IOController "1" -- "1" Validator
    IOController "1" -- "1" SentenceProcessor
    Sentence "*"--"1" SentenceProcessor
    SentenceProcessor "1" -- "1" Validator
    SentenceProcessor "1" -- "1" Analyzer
    SentenceProcessor "1" -- "1" SentenceGenerator
    TemplateGenerator "1" -- "1" Template
    TemplateController "1" -- "1" TemplateGenerator
    TemplateController "1" -- "1" WordPicker
    WordPicker "1" -- "1" SystemDictionary
    WordPicker "1" -- "1" SentenceProcessor
    ApiCaller "1" -- "1" Validator
    ApiCaller "1" -- "1" Analyzer

@enduml