@startuml Design Model

    class IOController { /'OK'/
        inputSentence() : String
        showInputError() : void
        displaySentence(sentenceDesc : String, flag : int) : void
        showValidationError() : void
        showLanguageError() : void
        showSyntacticTree() : void
        showToxicityError() : void
        showToxicityResults(toxicityLevel : double) : void
    }

    class Sentence { /'OK'/
        sentenceDesc : String
        <<syntacticTree>>
        create(sentenceDesc : String) : Sentence
        /' NUOVA
        sentenceDesc : String
        <<syntacticTree>> : SyntacticNode
        getSentenceTree(syntacticTree : SyntacticNode) : void
        getSentenceDesc() : String
        getSentenceTree() : SyntacticNode
        '/
    }

    class SentenceProcessor { /'OK'/
        inputSentence : Sentence
        nonSenseSentence : Sentence
        tempSentence : Sentence
        state : boolean
        createSentence(sentenceDesc : String) : void
        getSyntacticTree() : SyntacticNode
    }
    
    class Validator { /'OK'/
        verifySentence(input : String) : boolean
        validateSentenceStructure(SyntacticNode : <<syntacticTree>>) : boolean
        verifyToxicity(sentenceDesc : String) : boolean
    }

    class Analyzer { /'OK'/
        analyzeSentence(sentenceDesc : String) : void
        buildSyntacticTree(jsonInput : String) : SyntacticNode
    }

    class ApiCaller { /'OK'/
        getApiKey() : String
        getSyntaxAnalysis(sentenceDesc : String) : String
        getToxicityAnalysis(sentenceDesc : String) : String
        makeCall(url : String, payload : String) : String
    }

    /'GoogleAPI non è realmente una classe del nostro sistema'/

    class Template { /'OK'/
        templateDesc : String
        templateWords : int[]
        create(randomStructure : String) : Template
    }

    class TemplateController { /'OK'/
        template : Template
        getWordCount() : int[]
        getTemplateDesc() : String
    }

    class TemplateGenerator { /'OK'/
        SentenceStructures : SentenceStructures
        generateTemplate() : Template
    }

    class SentenceStructures { /'OK'/
        <<structures>> : File
        getRandomStructure() : String
    }
    
    class Nouns { /'OK'/
        nouns : List<String>
        getNouns(count : int) : List<String>
        getNounsCount() : int
    }

    class Verbs { /'OK'/
        verbs : List<String>
        getVerbs(count : int) : List<String>
        getVerbsCount() : int
    }

    class Adjectives { /'OK'/
        adjectives : List<String>
        getAdjectives(count : int) : List<String>
        getAdjectivesCount() : int
    }

    class SystemDictionary { /'OK'/
        nouns : Nouns
        verbs : Verbs
        adjectives : Adjectives
        createDictionary(nouns : List<String>, verbs : List<String>, adjectives : List<String>) : Dictionary<K,V>
        setupWordDic() : void
        initializeDic() : void
        pickDictionaryWords(words : int[]) : Dictionary<K,V>
        getDictionaryWordsCount() : Map<String, Integer>
    }
    
    class WordPicker { /'OK'/
        pickSentenceWords(senWords : int[]) : String[]
        getWords() : Dictionary<K,V>
    }

    class SentenceGenerator { /'OK'/
        generateSentenceDesc(templateDesc : String, words : Dictionary<K,V>) : String
    }

    SentenceStructures o- TemplateGenerator
    Nouns -* SystemDictionary
    Verbs -* SystemDictionary
    Adjectives -* SystemDictionary

    IOController "1" -- "1" Validator
    IOController "1" -- "1" SentenceProcessor
    Sentence "*"--"1" SentenceProcessor
    SentenceProcessor "1" -- "1" Validator
    SentenceProcessor "1" -- "1" Analyzer
    SentenceProcessor "1" -- "1" SentenceGenerator
    TemplateGenerator "1" -- "1" Template
    TemplateController "1" -- "1" TemplateGenerator
    TemplateController "1" -- "1" WordPicker
    WordPicker "1" -- "1" SystemDictionary
    WordPicker "1" -- "1" SentenceProcessor
    ApiCaller "1" -- "1" Validator
    ApiCaller "1" -- "1" Analyzer

@enduml